#!/usr/bin/env node

import { mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

import {
  contextDigest,
  loadStartupContext,
  validatePublicArtifact,
  validateStartupContext,
} from "./lib.mjs";

function metadata(context, digest) {
  return `<!-- generated from .agents/startup-context.json; do not edit -->\ncontext-version: ${context.context_version}\ncontext-digest: ${digest}\n`;
}

function markdownArtifacts(context, digest) {
  const head = metadata(context, digest);
  const product = context.product.name;
  const oneLiner = context.product.one_liner;
  const mission = context.product.mission;
  const vision = context.product.vision;
  const founderRevenue = context.traction.founder_attested_revenue.display;
  const localDelivery = context.delivery.local;
  const cloudDelivery = context.delivery.cloud;
  const productUrl = context.links.product.url;
  const repositoryUrl = context.links.repository.url;
  const telegramUrl = context.links.telegram.url;
  const answers = context.application_answers;

  return {
    "README.md": `${head}\n# ${product} fundraising application kit\n\nThis directory is generated from the repository-owned startup context. Adapt semantic answers to each program's official questions, but never change product facts, links, evidence, or claims without updating and validating the source context.\n\n- Product: ${product}\n- Product page: ${productUrl}\n- Repository: ${repositoryUrl}\n- Telegram: ${telegramUrl}\n- Demo video: not verified; do not attach\n- Founder video: not verified; do not attach\n- Pitch deck: \`deck.pdf\` (attach only when \`deck.pdf.receipt.json\` matches the current context digest)\n\nPast submissions are historical evidence, not a source for new answers.\n`,
    "answers.en.md": `${head}\n# ${product} — canonical fundraising answers\n\n## One word\n\n${answers.one_word}\n\n## Describe the company in 50 characters or less\n\n${answers.short_description}\n\n## What is the product?\n\n${oneLiner}\n\n## What problem are you solving?\n\n${answers.problem}\n\n## How do you solve it?\n\n${answers.solution}\n\n## Why are you building this?\n\n${answers.why_building}\n\n## How far along are you?\n\n${answers.progress}\n\n## Who is the market?\n\n${answers.market}\n\n## How do you make money?\n\n${answers.business_model}\n\n## What is different?\n\n${answers.differentiation}\n\n## How are you building it?\n\n${answers.how_built}\n\n## How will you use the funds?\n\n${answers.use_of_funds}\n\n## Mission and long-term vision\n\n${mission} ${vision}\n\n## Verified delivery and traction boundary\n\n${localDelivery} ${cloudDelivery} Founder-attested revenue is ${founderRevenue}; never relabel it as MRR or ARR without period evidence.\n\n## Links\n\n- Product: ${productUrl}\n- Repository: ${repositoryUrl}\n- Telegram: ${telegramUrl}\n`,
    "answers.ja.md": `${head}\n# ${product} — 資金調達応募の正本回答\n\n## 何を作っていますか\n\n${product}は、身体・心・お金と現実のfollow-throughを管理し、委任範囲で行動して、証拠付きの結果をTelegramへ返すproactive general agentです。\n\n## 何をしますか\n\nDaily Organは予定と応募を進め、Physical / Mental Organは生活習慣とwellbeingを支え、Financial Organは総資産、収支、支出、収入機会、crypto、riskを制御した資産運用を管理します。提案だけで終わらず、許可された行動を実行し、receiptを保存します。\n\n## Missionと長期vision\n\n${mission} ${vision}\n\n## なぜ今ですか\n\nmodelは推論とtool利用ができる一方、userの目標はCalendar、form、金融口座、dashboardの間で止まります。${product}は一つの証拠台帳とmanager体験でそれらを接続します。\n\n## 何が違いますか\n\n助言や可視化だけで止まりません。委任された行動を実行し、完了を独立検証し、証拠のない試行を成功と報告しません。localとcloudは同じcoreです。\n\n## 現在地\n\nrepositoryとTelegram入口は公開されています。local / cloud componentと複数の専門loopはrepositoryに存在します。founder証言では、${product}はfounderへ${founderRevenue}の収益を生み出しています。期間証拠なしにMRRやARRとは呼びません。\n\n## Business model\n\n${localDelivery} ${cloudDelivery}\n\n## 導線\n\n- Product: ${productUrl}\n- Repository: ${repositoryUrl}\n- Telegram: ${telegramUrl}\n`,
    "deck.md": `${head}\n# ${product} deck source\n\n## 1 — Life Manager\n\nA proactive general agent for body, mind, money, and real-world follow-through.\n\n## 2 — Problem\n\nPeople know what would improve their lives, but action stops between disconnected calendars, forms, health routines, and financial accounts.\n\n## 3 — Product\n\nOne manager coordinates specialist organs, executes within delegated boundaries, verifies the result, and reports in Telegram.\n\n## 4 — Daily Organ\n\nCalendar, event and accelerator applications, job applications, priorities, and follow-through.\n\n## 5 — Physical / Mental Organ\n\nRoutines, wellbeing, and continuity of care.\n\n## 6 — Financial Organ\n\nNet worth, cash flow, expense management, income opportunities, crypto, and risk-managed investing.\n\n## 7 — Trust architecture\n\nLeast privilege, deterministic money arithmetic, typed state transitions, receipts, and fail-closed reporting.\n\n## 8 — Delivery\n\n${localDelivery} ${cloudDelivery}\n\n## 9 — Current proof\n\nPublic repository and Telegram entry point. Founder-attested revenue generated by Life Manager: ${founderRevenue}.\n\n## 10 — Mission\n\n${mission}\n\n${productUrl}\n${repositoryUrl}\n${telegramUrl}\n`,
    "one-pager.md": `${head}\n# ${product}\n\n${oneLiner}\n\n## The problem\n\nA person's life is split across calendars, applications, health routines, bank accounts, investments, and dashboards. Advice is abundant; dependable execution and verification are scarce.\n\n## The product\n\n${product} coordinates a Daily Organ, a Physical / Mental Organ, and a Financial Organ. It uses specialist agents for semantic work and deterministic code for arithmetic, state, permissions, and receipts. The user gets concise Telegram reports with tappable evidence links.\n\n## Mission\n\n${mission} ${vision}\n\n## The wedge\n\nBegin with one founder's local runtime and measurable real-world outcomes. The founder attests that ${product} has already generated ${founderRevenue} in revenue. Offer the same core in both forms: ${localDelivery} ${cloudDelivery}\n\n## Trust\n\nLeast privilege, owner-separated accounts, no invented success, no guaranteed financial returns, and explicit provenance for founder-attested versus provider-verified claims.\n\n## Links\n\n- ${productUrl}\n- ${repositoryUrl}\n- ${telegramUrl}\n`,
  };
}

function pdfText(value) {
  return value
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, "-")
    .replaceAll("\\", "\\\\")
    .replaceAll("(", "\\(")
    .replaceAll(")", "\\)");
}

function wrapText(value, width = 72) {
  const lines = [];
  for (const paragraph of value.split(/\n+/).map((line) => line.trim()).filter(Boolean)) {
    let line = "";
    for (const word of paragraph.split(/\s+/)) {
      if (line && `${line} ${word}`.length > width) {
        lines.push(line);
        line = word;
      } else {
        line = line ? `${line} ${word}` : word;
      }
    }
    if (line) lines.push(line);
  }
  return lines;
}

function renderDeckPdf(markdown, context, digest) {
  const sections = markdown.split(/^## /m).slice(1).map((section) => {
    const [title, ...body] = section.trim().split("\n");
    return { title, lines: wrapText(body.join("\n")) };
  });
  const pageObjectIds = sections.map((_, index) => 3 + index * 2);
  const fontObjectId = 3 + sections.length * 2;
  const objects = [
    `<< /Type /Catalog /Pages 2 0 R >>`,
    `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${sections.length} >>`,
  ];

  for (const [index, section] of sections.entries()) {
    const pageId = pageObjectIds[index];
    const contentId = pageId + 1;
    const body = section.lines.slice(0, 18)
      .map((line, lineIndex) => `1 0 0 1 72 ${410 - lineIndex * 24} Tm (${pdfText(line)}) Tj`)
      .join("\n");
    const stream = `BT\n/F1 28 Tf\n1 0 0 1 72 470 Tm (${pdfText(section.title)}) Tj\n/F1 15 Tf\n${body}\nET`;
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 720 540] /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> /Contents ${contentId} 0 R >>`);
    objects.push(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);
  }
  objects.push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);

  let pdf = `%PDF-1.4\n% context-version: ${context.context_version}\n% context-digest: ${digest}\n`;
  const offsets = [0];
  for (const [index, object] of objects.entries()) {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("");
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(pdf, "ascii");
}

export async function buildApplicationKit({ context, outputDirectory }) {
  const errors = validateStartupContext(context);
  if (errors.length > 0) throw new Error(`Invalid startup context:\n${errors.join("\n")}`);

  const digest = contextDigest(context);
  const artifacts = markdownArtifacts(context, digest);
  const assets = {
    context_version: context.context_version,
    context_digest: digest,
    assets: [
      { type: "product", status: "verified", url: context.links.product.url },
      { type: "repository", status: "verified", url: context.links.repository.url },
      { type: "telegram", status: "verified", url: context.links.telegram.url },
    ],
    excluded: [
      { type: "dashboard", status: context.links.dashboard.status, reason: context.links.dashboard.evidence },
      { type: "demo_video", status: context.links.demo.status, reason: context.links.demo.evidence },
      { type: "founder_video", status: context.links.founder_video.status, reason: context.links.founder_video.evidence },
    ],
  };
  artifacts["assets.json"] = `${JSON.stringify(assets, null, 2)}\n`;

  for (const [file, content] of Object.entries(artifacts)) {
    const artifactErrors = validatePublicArtifact(content, context);
    if (artifactErrors.length > 0) {
      throw new Error(`${file} failed public artifact validation:\n${artifactErrors.join("\n")}`);
    }
  }

  const deckPdf = renderDeckPdf(artifacts["deck.md"], context, digest);
  artifacts["deck.pdf"] = deckPdf;
  artifacts["deck.pdf.receipt.json"] = `${JSON.stringify({
    schema_version: 1,
    context_version: context.context_version,
    context_digest: digest,
    source: "fundraising/application-kit/deck.md",
    pdf_sha256: createHash("sha256").update(deckPdf).digest("hex"),
  }, null, 2)}\n`;

  await mkdir(outputDirectory, { recursive: true });
  for (const [file, content] of Object.entries(artifacts)) {
    await writeFile(resolve(outputDirectory, file), content, Buffer.isBuffer(content) ? undefined : "utf8");
  }

  return {
    context_version: context.context_version,
    context_digest: digest,
    files: Object.keys(artifacts).sort(),
  };
}

async function main() {
  const contextPath = new URL("../../.agents/startup-context.json", import.meta.url);
  const outputDirectory = fileURLToPath(new URL("../../fundraising/application-kit/", import.meta.url));
  const context = await loadStartupContext(contextPath);
  const result = await buildApplicationKit({ context, outputDirectory });
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  await main();
}
