#!/usr/bin/env bash
# Sourced by every Writer entrypoint. One contract for repository code,
# mutable state, logs and credentials in both local and cloud runtimes.

WRITER_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
_WRITER_ROOT_CALLER="${ARTICLE_ROOT:-${ARTICLE_SKILL_DIR:-$(cd "$WRITER_SCRIPT_DIR/.." && pwd -P)}}"
_WRITER_REPO_CALLER="${LIFE_MANAGER_REPO:-$(cd "$_WRITER_ROOT_CALLER/../.." && pwd -P)}"
_WRITER_STATE_CALLER="${WRITER_STATE_DIR:-${ARTICLE_STATE_DIR:-${LIFE_MANAGER_STATE_ROOT:-$HOME/.local/state/life-manager/writer}}}"
_WRITER_LOG_CALLER="${WRITER_LOG_DIR:-$_WRITER_STATE_CALLER/logs}"
_WRITER_ENV_CALLER="${LIFE_MANAGER_ENV_FILE:-$HOME/.local/state/life-manager/.env}"
_WRITER_PYTHON_CALLER="${LIFE_MANAGER_PYTHON:-$(command -v python3)}"
_WRITER_BROWSER_PYTHON_CALLER="${WRITER_BROWSER_PYTHON:-$_WRITER_PYTHON_CALLER}"
_WRITER_CLOAK_PYTHON_CALLER="${WRITER_CLOAK_PYTHON:-$_WRITER_BROWSER_PYTHON_CALLER}"

# shellcheck source=../../../apps/life-manager/scripts/lib/load-env-file.sh
source "$_WRITER_REPO_CALLER/apps/life-manager/scripts/lib/load-env-file.sh"
lm_load_env_file "$_WRITER_ENV_CALLER"

# Dotenv contains credentials, never path ownership. Preserve the caller's
# immutable release and registry-selected writable roots across sourcing.
WRITER_ROOT="$_WRITER_ROOT_CALLER"
LIFE_MANAGER_REPO="$_WRITER_REPO_CALLER"
WRITER_STATE_DIR="$_WRITER_STATE_CALLER"
WRITER_LOG_DIR="$_WRITER_LOG_CALLER"
LIFE_MANAGER_ENV_FILE="$_WRITER_ENV_CALLER"
LIFE_MANAGER_PYTHON="$_WRITER_PYTHON_CALLER"
WRITER_BROWSER_PYTHON="$_WRITER_BROWSER_PYTHON_CALLER"
WRITER_CLOAK_PYTHON="$_WRITER_CLOAK_PYTHON_CALLER"
unset _WRITER_ROOT_CALLER _WRITER_REPO_CALLER _WRITER_STATE_CALLER
unset _WRITER_LOG_CALLER _WRITER_ENV_CALLER _WRITER_PYTHON_CALLER
unset _WRITER_BROWSER_PYTHON_CALLER _WRITER_CLOAK_PYTHON_CALLER

case "$WRITER_STATE_DIR/$WRITER_LOG_DIR" in
  *"/.openclaw/"*|*"/.hermes/"*)
    printf 'writer runtime refuses legacy state/log roots\n' >&2
    return 1
    ;;
esac
ARTICLE_ROOT="$WRITER_ROOT"
ARTICLE_SKILL_DIR="$WRITER_ROOT"
ARTICLE_STATE_DIR="$WRITER_STATE_DIR"
STATE_DIR="$WRITER_STATE_DIR"
NOTE_MCP_DIR="$WRITER_ROOT/vendor/note-mcp"
NOTE_MCP_SRC="$NOTE_MCP_DIR/src"
PYTHONPATH="$NOTE_MCP_SRC${PYTHONPATH:+:$PYTHONPATH}"
export LIFE_MANAGER_REPO LIFE_MANAGER_ENV_FILE LIFE_MANAGER_PYTHON WRITER_ROOT WRITER_STATE_DIR WRITER_LOG_DIR
export ARTICLE_ROOT ARTICLE_SKILL_DIR ARTICLE_STATE_DIR STATE_DIR WRITER_BROWSER_PYTHON WRITER_CLOAK_PYTHON
export NOTE_MCP_DIR NOTE_MCP_SRC PYTHONPATH
